server:
  context-path: /myprofile
  port: 8091
spring:
  application:
    name: BootMongo
  data:
    mongodb:
      database: myprofile_db
      host: localhost
      port: 27017
jsi:
  rabbitmq:
    queue: jsi.queue1
    exchange: jsi.direct1
    routingkey: jsi.routingkey1