server:
  port: 8091
#  context-path: /myprofile
#  ports:
#    http: 8033
#  port: 8091
#  ssl:
#    key-store: keystore.p12
#    key-store-password: root123
#    keyStoreType: PKCS12
#    keyAlias: tomcat

security:
  require-ssl: true

spring:
  application:
    name: BootMongo
  data:
    mongodb:
      database: myprofile_db
      host: localhost
      port: 27017
jsi:
  rabbitmq:
    queue: jsi.queuereg
    exchange: jsi.directreg
    routingkey: jsi.routingkeyreg